### ISSUE TITLE
Unable to install (inconsistency in package versions)

### ISSUE THREAD

**Issue by ghost** [timwedde/composer#7]
Hello,

What version of Python3 did you test with your package? I have tried Python 3.5, 3.6, ... so on, but unable to get the installation to complete because of inconsistency in package versions, for example in `MarkupSafe`, `matplotlib`, `bleach`, `tensorboard`, etc. I was unable to get it to install after spending several hours trying various versions since you didn't specify the version of Python. Could you update your [requirements.txt](https://github.com/timwedde/composer/blob/master/requirements.txt) file or make a conda envinronment file (`.yml`)?

**Comment by timwedde** [comment]
Well, it's not a package per-se, more an amalgamation of the work I did for my bachelor thesis.
It's been a few years since I did this project and unfortunately, due to time constraints, I haven't done much with it past that.
Problematically it appears that the Tensorflow Magenta package I was using has changed so drastically (and apparently their deployment scheme as well) that it's not the same as what it was when this project happened. As such I believe it will be very difficult to get this to run as-is. I would probably have to sit down and port it over to the new versions of these packages as they are now, which would take me quite a while.

To be honest I'm not sure whether this would be a worthwhile endeavor, given that there's several projects that have been released in the meantime which are much better than this is. MusicVAE for example came out right after this and provided better output. In the years after that, more work has been done (especially using Transformers), so in my opinion it would probably be a better approach to restart this project from scratch using newer and better technologies instead of trying to frankenstein this one.

**Comment by ghost** [comment]
Thanks for the clarification. Although I wasted my time trying to figure out a way to install, it might be helpful to mention what you said in the readme file for others so they know what they are getting into before spending their time unlike me.
